name: yox
version: 0.0.13
homepage: https://github.com/codekaze/yo
description: ---
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  process_run: ^0.12.1
  args: ^2.0.0
  path: ^1.7.0
  intl: ^0.17.0
  ftpconnect: ^1.0.0
  uuid: ^3.0.4
  http:
  
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4
executables: 
  yox: 
analyzer: 
  exclude: 
    - assets/**
    - test/*.g.dart